[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  HUGO_VERSION = "0.66.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

# [context.production]
#   command = "npm run build && npm run ipfs-deploy"

[[redirects]]
  from = "https://www.suncook.men/*"
  to = "https://www.suncook.men/:splat"
  force = true
